version: '3.1'
services:
  db:
    image: postgres
    container_name: kandidat.db
    restart: unless-stopped
    volumes:
      - "postgres-data:/var/lib/postgresql/data:delegated"
      - "./db:/docker-entrypoint-initdb.d"
    ports:
      - "${DATABASE_HOST:-127.0.0.1}:${DATABASE_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-backend-db}
      - POSTGRES_USER=${POSTGRES_USER:-dbuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-kandidat-backend}

  adminer:
    image: adminer
    container_name: kandidat.adminer
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:8080"

volumes:
  postgres-data:
    driver: local

